# Generated by Django 2.1.7 on 2021-08-21 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='essay_style',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='mc_type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mc_id', models.IntegerField(default=0, null=True)),
                ('type', models.CharField(max_length=256, null=True)),
                ('type_name', models.CharField(default='', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='micro_course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('c_name', models.CharField(default='', max_length=256)),
                ('c_path', models.CharField(default='', max_length=256)),
                ('create_time', models.DateTimeField(verbose_name='date published')),
                ('t_id', models.IntegerField(default=0, null=True)),
                ('c_desc', models.CharField(max_length=3000, null=True)),
                ('type', models.CharField(max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='model_essay',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('es_id', models.IntegerField(default=0, null=True)),
                ('title', models.CharField(max_length=256, null=True)),
                ('content', models.CharField(max_length=3000, null=True)),
                ('writing_theme', models.CharField(max_length=256, null=True)),
                ('tea_id', models.IntegerField(default=0, null=True)),
                ('create_time', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='stu_course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('s_id', models.IntegerField(default=0, null=True)),
                ('mc_id', models.IntegerField(default=0, null=True)),
                ('process', models.CharField(max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='stu_writing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('wt_id', models.IntegerField(default=0, null=True)),
                ('s_id', models.IntegerField(default=0, null=True)),
                ('content', models.CharField(max_length=3000, null=True)),
                ('writing_theme', models.CharField(max_length=256, null=True)),
                ('notes', models.CharField(max_length=3000)),
                ('tea_score', models.CharField(max_length=256)),
                ('total_score', models.CharField(max_length=256)),
                ('machine_score', models.CharField(max_length=256)),
                ('finish_time', models.DateTimeField(verbose_name='date published')),
                ('practice_type', models.IntegerField(default=0, null=True)),
                ('is_upload', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(default='', max_length=256)),
                ('pass_wd', models.CharField(default='', max_length=256)),
                ('join_time', models.DateTimeField(verbose_name='date published')),
                ('tel_number', models.CharField(max_length=256, null=True)),
                ('zh_name', models.CharField(max_length=256, null=True)),
                ('en_name', models.CharField(max_length=256, null=True)),
                ('gender', models.CharField(max_length=4, null=True)),
                ('nationality', models.CharField(max_length=256, null=True)),
                ('zh_proficiency', models.CharField(max_length=256, null=True)),
                ('college_major', models.CharField(max_length=128, null=True)),
                ('stu_category', models.CharField(max_length=128, null=True)),
                ('records', models.CharField(max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tea_admin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(default='', max_length=256)),
                ('pass_wd', models.CharField(default='', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='writing_task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('es_id', models.IntegerField(default=0, null=True)),
                ('title', models.CharField(max_length=256, null=True)),
                ('requirement', models.CharField(max_length=256, null=True)),
                ('finish_time', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
