# Generated by Django 2.1.7 on 2021-08-29 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srv', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='writing_task',
            name='finish_time',
        ),
        migrations.AddField(
            model_name='writing_task',
            name='deadline_time',
            field=models.CharField(default='', max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='micro_course',
            name='create_time',
            field=models.CharField(default='', max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='model_essay',
            name='create_time',
            field=models.CharField(default='', max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='stu_writing',
            name='finish_time',
            field=models.CharField(default='', max_length=45, null=True),
        ),
    ]
