# Generated by Django 2.1.7 on 2021-08-30 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srv', '0002_auto_20210829_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='writing_task',
            name='create_time',
            field=models.CharField(default='', max_length=45, null=True),
        ),
    ]
