# Generated by Django 2.1.7 on 2021-09-04 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srv', '0003_writing_task_create_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='stu_writing',
            name='create_time',
            field=models.CharField(default='', max_length=45, null=True),
        ),
    ]
